### PR TITLE
Add Options JSON for configuration

### PR DESCRIPTION
**Pull request by ebspeter**
Adding ability to configure JSON options for LayoutComponents in the same way as on fields in Collections. 

Ideally it should be in an accordion or modal to keep the form clean but i didn't have time to figure out how, UIkit elements don't seem to work out of the box. Happy to work on that if you point me in the right direction or to documentation. 

The use-case i'm working on is to use [CustomComponents](https://github.com/pauloamgomes/Cockpit-CustomComponents) to specify which components can be added to a LayoutComponent which accepts children. This is needed because not all components are compatible with all other components in the front-end app (Nuxt). 

image

### CODE REVIEW

**Comment by fredrikkarlsson-pervanovo** [comment]
Since https://github.com/agentejo/cockpit/pull/1188 is merged in cockpit, I guess this can be merged as well @aheinze ?

**Comment by TulioAbreu** [comment]
Any updates on this feature?

**Comment by fredrikkarlsson-pervanovo** [comment]
Not much it seems. We are using this PR branch together with a modification of our own that adds custom icons to Layout components (https://github.com/Pervanovo/LayoutComponents/tree/integration). Hope this will get merged since it is really helpful when customizing LCs.

**Comment by aheinze** [comment]
Thanks for the contribution!

**Pull request merged**
